// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Motion_lie_detection
{
    
    #region Windows Form Designer generated code
    public partial class Window
    {
        private void InitializeComponent()
        {
            this.panel1 = new System.Windows.Forms.Panel();
            // 
            // panel1
            // 
            this.panel1.Name = "panel1";
            this.panel1.Location = new System.Drawing.Point(16, 24);
            this.panel1.TabIndex = 0;
            this.panel1.Size = new System.Drawing.Size(472, 576);
            this.panel1.BackColor = System.Drawing.SystemColors.ControlText;
            this.panel1.Text = "panel1";
            this.panel1.Paint += new System.Windows.Forms.PaintEventHandler(this.panel1_Paint);
			this.panel1.Click += this.panel1_Click;
            // 
            // Window
            // 
            this.Name = "Window";
            this.ClientSize = new System.Drawing.Size(511, 630);
            this.Controls.Add(this.panel1);
            this.Text = "Window";
			this.FormClosing += this.form_Closed;
        }
        private System.Windows.Forms.Panel panel1;
    }
    #endregion
}
